### ISSUE TITLE
Websocket Read Error

### ISSUE THREAD

**Issue by guanm326** [dougdellolio/coinbasepro-csharp#131] opened 2018-05-26 13:35 UTC
```
Exception thrown: 'GDAXSharp.Exceptions.GDAXSharpWebSocketException' in GDAXSharp.dll
An exception of type 'GDAXSharp.Exceptions.GDAXSharpWebSocketException' occurred in GDAXSharp.dll but was not handled in user code
WebSocket Feed Error: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine.

```

While running my application, I am getting the above error on the incoming contents from GDAX. I've experienced this before in other languages that also connect to GDAX websocket stream. I was wondering what is the best way to potentially work around it?

For my code, I am simply subscribing to both match and level2 channels.

Thanks,
Mike

**Comment by dougdellolio** [comment] 2018-05-26 13:58
does this happen for the entire connection? may be able to just watch for the closed connection and calling `Start` again on the Websocket.

this also may be related to #129. @BradForsythe have you seen this? I know you mentioned that they just drop subscriptions randomly too...

**Comment by michaelguan326** [comment] 2018-05-26 14:09
How do you differentiate between the entire connection verses the closed one? Or am I misunderstanding the question? I don't currently know what type of incorrect data is sent to me but I do agree that it may simply be a matter of me re-subscribing to the feed again.

I've definitely seen GDAX dropping packets. There are situations (in my python code base) where after some time, level2 updates for a price level don't even exist in my own orderbook representation. My program barfs.... Look forward to the implementation.

**Comment by dougdellolio** [comment] 2018-05-27 20:58
i haven't tried this but maybe have something around the `OnWebSocketError` or `OnWebSocketClose` eventhandlers.

i think re-subscribing might be the way for now. that implementation will be built in shortly. can keep this issue open until it is added.

**Comment by BradForsythe** [comment] 2018-05-29 00:52
I haven't seen this specific error "Unable to read data from the transport connection,,,"   I have seen Level2 updates freeze, I have seen connections forcibly closed by GDAX, but this seems like your host machine closed the connection.   In my case, I monitor and then close and restart the socket.   In your error, I think @dougdellolio suggestion should work, create your handler for the OnWebSocketError.     If the OnWebSocketClosed event fires, GDAXSharp will automatically try to reopen and subscribe so I am guessing this event isn't getting fired.   

 If you are getting an exception thrown, there is probably something else going on.  Look at the stack trace and where the error is originating.

Last week I was getting scrambled eggs on occasion from the level2 feed and newtonsoft was throwing an exception inside of GDAXSharp.    The safest option is to try catch the socket in cases like this and maybe yours, then restart.

**Comment by michaelguan326** [comment] 2018-05-29 18:12
Thanks for the answers. I have since modified the error handling both of my application side and on the Websocket side. I will let it run to see if I get any more errors.

On another note, I have been subscribing to the both "Match" and "Level2" channels. As the websocket receives messages via "WebSocket_MessageReceived", I have received a "Change" Message that is not one of the handled ResponseType which in turn caused an exception in the switch statement within web socket method "WebSocket_MessageReceived": 

`System.ArgumentOutOfRangeException: 'Specified argument was out of the range of valid values.'`

To my understanding, a Change message is only sent when you are subscribing to the full channel - which I am clearly not.  What do you think is the best way to handle this is? I am thinking of just creating a new EventHandler for this message type.

**Comment by BradForsythe** [comment] 2018-05-29 19:28
@michaelguan326,  I don't use the full channel.   I use L2, ticker channel and user channels to keep order book, matched trades and my order status.   I don't see "change" messages.    

Seems like change message occurs when the self-trade preservation changes your size...maybe this message is happening even if you are not subscribed to the full channel?

Probably should look to see why you are getting these messages, but in the interim you should catch the exception.   @dougdellolio maybe also a good idea to put in a handler for the change message?

**Comment by chrisw000** [comment] 2018-05-29 20:59
Just to add.... on the original error text:

"Unable to read data from the transport connection: An established connection was aborted by the software in your host machine."

The text comes from the Windows subsystem; error: **WSAECONNABORTED** It is referring to the server side of the connection when it says "host". 

However, the cause of the abort doesn't *HAVE* to be down to the actual server at the other end... it could be due to firewalls, proxy servers, routers, modems etc. having issues along the way.

The cause of the error is very hard to impossible to pin point. [This blog post](https://www.chilkatsoft.com/p/p_299.asp) give a good explanation of what it could be.

So whilst a auto recover feature is nice, I think for this sort of specific error, auto recovery is also masking an underlying network transport issue.

**Comment by chrisw000** [comment] 2018-05-29 21:04
@dougdellolio re 
....ResponseType which in turn caused an exception in the switch statement within web socket method "WebSocket_MessageReceived":

`System.ArgumentOutOfRangeException: 'Specified argument was out of the range of valid values.'`

The GDAX Docs says this:

> Please note that new message types can be added at any point in time. Clients are expected to ignore messages they do not support.

So the code shouldn't throw an exception here when it gets a message it doesn't know what to do with.... it should ignore the message.

**Comment by BradForsythe** [comment] 2018-05-29 21:56
@chrisw000   good catch on the GDAX docs.     I agree, we should ignore or add a handler for messages that aren't supported, instead of throwing an exception.

The "change" message would occur if you subscribe to User channel and you are trying to trade against yourself.  

Also, the "activate" message needs to be supported for stop orders.

**Comment by dougdellolio** [comment] 2018-05-30 23:16
ill take a look at this. agreed that it shouldn't throw an exception. now that we have logging we can log it and move forward.

**Closed** 2018-07-09 23:06 UTC
